# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1be1b18916fd789cc0e28037b797f541c5cd4c67d0c56084655616d74748479b7d232c9da05ec86ce6a3763a2ed9b32c0818d27bf6fd3d94fd3d9b64426a421c

test:
  secret_key_base: b11f6c52996aff7175c75e229549c13e454dc956970331d076ac58de8c2b256dc4ddcac763cc3e58b28f524ec4beaf1a59c92d80eadebaee6853738670b31af5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
